### ISSUE TITLE
How can I get the Java and Command Prompt Files

### ISSUE THREAD

**Issue by ludalm1** [Luxusio/ADOFAI-Macro#2]
# Why?!
So, I wanted to use the ADOFAI Macro, And I did watch the tutorial from the README.MD File. But then I noticed the there was no releases. Can you give me the download link of the ADOFAI Macro files?

**Comment by Thathip** [comment]
https://github.com/Thathip/ADOFAI-Macro-Working

**Comment by Luxusio** [comment]
This program can be considered as CHEAT PROGRAM.
CHEAT PROGRAM is not allowed by 7beat games, so I don't provide any program.
